const products = [
  {
    _id: "1",
    name: "Wireless Bluetooth Headphone",
    image: "/images/wireless-headphone.jpeg",
    description:
      "Ooberpad proudly announces the availability of Bowers & Wilkins (B&W) PX7 Over-ear Noise Cancelling Wireless Headphones. When you are on the go, experience music that is at a whole new, exhilarating level. Irrespective of where you are, powerful drivers and adaptive noise cancelling put you at the centrestage of the music.",
    brand: "Apple",
    category: "Electronics",
    price: "90.99",
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "2",
    name: "iphone 15 pro",
    image: "/images/iphone-15.jpg",
    description:
      "DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities — so you don’t miss them while you’re doing something else. You can see who’s calling, track your next ride, check your flight status, and so much more.",
    brand: "Apple",
    category: "Electronics",
    price: "500.99",
    countInStock: 10,
    rating: 4.8,
    numReviews: 4,
  },
  {
    _id: "3",
    name: "Wi-Fi Smart Camera",
    image: "/images/camera.jpeg",
    description:
      "Buy TP-LINK 2MP 1080p Full HD Home Security Wi-Fi Smart Camera Alexa Enabled 2-Way Audio Night Vision online in India at wholesale rates. If you have been looking for TP-LINK 2MP 1080p Full HD Home Security Wi-Fi Smart Camera Alexa Enabled 2-Way Audio Night Vision dealers, your search ends here as you can get the best TP-LINK 2MP 1080p Full HD Home Security Wi-Fi Smart Camera Alexa Enabled 2-Way Audio Night Vision distributors.",
    brand: "Apple",
    category: "Electronics",
    price: "850.50",
    countInStock: 5,
    rating: 3.5,
    numReviews: 3,
  },
  {
    _id: "4",
    name: "Smart speaker with Alexa",
    image: "/images/alexa.jpg",
    description:
      "3rd Generation Echo Dot-Smart Speaker with Alexa that can be operated by voice. Alexa can speak English and Hindi Just ask Alexa to play music from Amazon Music, Hungama, Spotify, Jio Saavn, Apple Music.",
    brand: "Amazon",
    category: "Electronics",
    price: "800.99",
    countInStock: 8,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: "5",
    name: "Wave Edge Smart Watch",
    image: "/images/smart-watch.jpg",
    description:
      "3rd Generation Echo Dot-Smart Speaker with Alexa that can be operated by voice. Alexa can speak English and Hindi Just ask Alexa to play music from Amazon Music, Hungama, Spotify, Jio Saavn, Apple Music.",
    brand: "boAt",
    category: "Electronics",
    price: "750.9",
    countInStock: 6,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: "6",
    name: "Airpode",
    image: "/images/airpode.jpeg",
    description:
      "3rd Generation Echo Dot-Smart Speaker with Alexa that can be operated by voice. Alexa can speak English and Hindi Just ask Alexa to play music from Amazon Music, Hungama, Spotify, Jio Saavn, Apple Music.",
    brand: "Amazon",
    category: "Electronics",
    price: "800.99",
    countInStock: 8,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: "7",
    name: "Alexa",
    image: "/images/alexa.jpg",
    description:
      "3rd Generation Echo Dot-Smart Speaker with Alexa that can be operated by voice. Alexa can speak English and Hindi Just ask Alexa to play music from Amazon Music, Hungama, Spotify, Jio Saavn, Apple Music.",
    brand: "Amazon",
    category: "Electronics",
    price: "800.99",
    countInStock: 8,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: "8",
    name: "wireless speaker",
    image: "/images/wireless-speaker.jpeg",
    description:
      "3rd Generation Echo Dot-Smart Speaker with Alexa that can be operated by voice. Alexa can speak English and Hindi Just ask Alexa to play music from Amazon Music, Hungama, Spotify, Jio Saavn, Apple Music.",
    brand: "Amazon",
    category: "Electronics",
    price: "800.99",
    countInStock: 8,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: "9",
    name: "iphone 15",
    image: "/images/iphone-15.jpg",
    description:
      "3rd Generation Echo Dot-Smart Speaker with Alexa that can be operated by voice. Alexa can speak English and Hindi Just ask Alexa to play music from Amazon Music, Hungama, Spotify, Jio Saavn, Apple Music.",
    brand: "Amazon",
    category: "Electronics",
    price: "800.99",
    countInStock: 8,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: "10",
    name: "wireless speaker",
    image: "/images/wireless-speaker.jpeg",
    description:
      "3rd Generation Echo Dot-Smart Speaker with Alexa that can be operated by voice. Alexa can speak English and Hindi Just ask Alexa to play music from Amazon Music, Hungama, Spotify, Jio Saavn, Apple Music.",
    brand: "Amazon",
    category: "Electronics",
    price: "800.99",
    countInStock: 8,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: "3",
    name: "Wi-Fi Smart Camera",
    image: "/images/camera.jpeg",
    description:
      "Buy TP-LINK 2MP 1080p Full HD Home Security Wi-Fi Smart Camera Alexa Enabled 2-Way Audio Night Vision online in India at wholesale rates. If you have been looking for TP-LINK 2MP 1080p Full HD Home Security Wi-Fi Smart Camera Alexa Enabled 2-Way Audio Night Vision dealers, your search ends here as you can get the best TP-LINK 2MP 1080p Full HD Home Security Wi-Fi Smart Camera Alexa Enabled 2-Way Audio Night Vision distributors.",
    brand: "Apple",
    category: "Electronics",
    price: "850.50",
    countInStock: 5,
    rating: 3.5,
    numReviews: 3,
  },
];

export default products;
